# Generated by Django 3.1 on 2020-08-29 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=10)),
                ('on_off', models.CharField(choices=[('사용중', '사용중'), ('빈강의실', '빈강의실')], default='빈강의실', max_length=50)),
                ('day_of_the_week', models.CharField(choices=[('mon', '월'), ('tue', '화'), ('wed', '수'), ('thu', '목'), ('fri', '금')], default='월', max_length=20)),
                ('available_time', models.TimeField(default='')),
                ('floor', models.TextField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(default='', max_length=100)),
                ('start_time', models.TimeField(default='')),
                ('finish_time', models.TimeField(default='')),
                ('floor', models.TextField(default='', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_room', to='Building_list.room')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=100)),
                ('start_time', models.TimeField(default='')),
                ('finish_time', models.TimeField(default='')),
                ('number', models.CharField(default='', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_room', to='Building_list.room')),
            ],
        ),
    ]
