# Generated by Django 3.1 on 2020-08-28 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=10)),
                ('floor', models.CharField(default='', max_length=10)),
                ('class_time', models.CharField(default='', max_length=20)),
                ('available_time', models.CharField(default='', max_length=20)),
                ('on_off', models.CharField(choices=[('사용중', '사용중'), ('빈강의실', '빈강의실')], default='빈강의실', max_length=50)),
                ('day_of_the_week', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(default='', max_length=100)),
                ('use_time', models.CharField(default='', max_length=20)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_list', to='Building_list.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', max_length=200)),
                ('lecture', models.ManyToManyField(to='Building_list.Lecture')),
            ],
        ),
    ]
