# Generated by Django 3.1 on 2020-08-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='floor',
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='day_of_the_week',
            field=models.CharField(choices=[('mon', '월'), ('tue', '화'), ('wed', '수'), ('thu', '목'), ('fri', '금')], default='월', max_length=20),
        ),
    ]
