# Generated by Django 3.0.8 on 2020-08-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='img',
            field=models.ImageField(blank=True, upload_to='timeline_photo/%Y/%m/%d'),
        ),
    ]
