# Generated by Django 3.1 on 2020-08-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='day_of_the_week',
            field=models.CharField(choices=[('월', '월'), ('화', '화'), ('수', '수'), ('목', '목'), ('금', '금'), ('토', '토'), ('일', '일')], default='월', max_length=20),
        ),
    ]
