# Generated by Django 3.1 on 2020-08-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building_list', '0002_auto_20200828_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
