# Generated by Django 3.0.8 on 2020-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Building_list', '0002_room_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='img',
            field=models.ImageField(upload_to='timeline_photo/%Y/%m/%d'),
        ),
    ]
