# Generated by Django 3.1 on 2020-08-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Building_list', '0003_auto_20200829_0734'),
        ('Building_list', '0003_auto_20200829_0649'),
    ]

    operations = [
    ]
